# Generated by Django 4.2.27 on 2026-01-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='semester',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
