# Generated by Django 4.2.27 on 2025-12-27 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meet', '0002_event_gender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('TRACK', 'Track'), ('FIELD', 'Field'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='gender_boys',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='gender_girls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='max_team_size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='min_team_size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('TEAM', 'Team')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.CreateModel(
            name='MeetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meet.event')),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meet_events', to='meet.meet')),
            ],
            options={
                'unique_together': {('meet', 'event')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='event',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='event',
            name='meet',
        ),
        migrations.AddField(
            model_name='registration',
            name='meet_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='meet.meetevent'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('meet_event', 'participant')},
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_created', to=settings.AUTH_USER_MODEL)),
                ('meet_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='meet.meetevent')),
                ('members', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('meet_event', 'name')},
            },
        ),
        migrations.RemoveField(
            model_name='registration',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='event',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='registered_by',
        ),
    ]
