# Generated by Django 4.2.27 on 2025-12-27 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0003_alter_event_unique_together_event_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='meet_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='meet.meetevent'),
        ),
    ]
