# Generated by Django 4.2.27 on 2025-12-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0004_alter_registration_meet_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetevent',
            name='gender_boys',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetevent',
            name='gender_girls',
            field=models.BooleanField(default=False),
        ),
    ]
