# Generated by Django 4.2.27 on 2025-12-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0006_remove_team_members_meetevent_max_team_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='gender_boys',
        ),
        migrations.RemoveField(
            model_name='event',
            name='gender_girls',
        ),
    ]
