# Generated by Django 4.2.27 on 2026-01-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0007_remove_event_gender_boys_remove_event_gender_girls'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
