# Generated by Django 4.2.27 on 2026-01-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0008_registration_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetevent',
            name='gender_boys',
        ),
        migrations.RemoveField(
            model_name='meetevent',
            name='gender_girls',
        ),
        migrations.RemoveField(
            model_name='meetevent',
            name='max_team_size',
        ),
        migrations.RemoveField(
            model_name='meetevent',
            name='min_team_size',
        ),
        migrations.AddField(
            model_name='event',
            name='gender_boys',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='gender_girls',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_team_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='min_team_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
