# Generated by Django 4.2.27 on 2026-01-05 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0009_remove_meetevent_gender_boys_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='gender_boys',
        ),
        migrations.RemoveField(
            model_name='event',
            name='gender_girls',
        ),
        migrations.RemoveField(
            model_name='event',
            name='min_team_size',
        ),
    ]
