# Generated by Django 4.2.27 on 2026-01-06 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_semester'),
        ('meet', '0010_remove_event_gender_boys_remove_event_gender_girls_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='team',
            name='department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.department'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('meet_event', 'department')},
        ),
        migrations.RemoveField(
            model_name='team',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
    ]
