# Generated by Django 4.2.27 on 2026-01-06 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0011_alter_team_unique_together_team_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='is_captain',
        ),
    ]
